### ISSUE TITLE
Prevent client from closing on promotion

### ISSUE THREAD

**Issue by byotta** [WoedWoef/NoLooksies#7]
Suppose user promotes from plat -> diamond, diamond -> master etc

Allow client to continue running in this case, so user can see promotion animation

This could be an option to enable/disable, since some users may not want to know about promotion. This one may be the endpoint to use but I haven't investigated much

https://www.mingweisamuel.com/lcu-schema/tool/#/Plugin%20lol-ranked/PostLolRankedV1NotificationsByIdAcknowledge

**Comment by WoedWoef** [comment]
Hey! yeah I want to implement this but I'm kinda wary of doing it before the new split, as i'm not sure if the API is gonna change because of the new rank and removal of promo's and all that. So I kinda wanted to wait untill that time comes to update it. I did however add functionality for honoring teammates before the client closes, if that's something you're interested in. (should be under the pre-release in the releases)

**Comment by byotta** [comment]
Awesome thank you!

**Comment by WoedWoef** [comment]
Solved with the new version, when you go up a rank it shows the little animation.
